# Install script for directory: C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata

# Set the install prefix
IF(NOT DEFINED CMAKE_INSTALL_PREFIX)
  SET(CMAKE_INSTALL_PREFIX "C:/Work/dcmtk-3.5.4/../dcmtk-3.5.4-win32-i386")
ENDIF(NOT DEFINED CMAKE_INSTALL_PREFIX)
STRING(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
IF(NOT CMAKE_INSTALL_CONFIG_NAME)
  IF(BUILD_TYPE)
    STRING(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  ELSE(BUILD_TYPE)
    SET(CMAKE_INSTALL_CONFIG_NAME "Release")
  ENDIF(BUILD_TYPE)
  MESSAGE(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
ENDIF(NOT CMAKE_INSTALL_CONFIG_NAME)

# Set the component getting installed.
IF(NOT CMAKE_INSTALL_COMPONENT)
  IF(COMPONENT)
    MESSAGE(STATUS "Install component: \"${COMPONENT}\"")
    SET(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  ELSE(COMPONENT)
    SET(CMAKE_INSTALL_COMPONENT)
  ENDIF(COMPONENT)
ENDIF(NOT CMAKE_INSTALL_COMPONENT)

FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/cmdlnarg.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcbytstr.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcchrstr.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dccodec.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcdatset.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcddirif.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcdebug.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcdefine.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcdeftag.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcdicdir.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcdicent.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcdict.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcdirrec.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcelem.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcerror.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcfilefo.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dchashdi.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcistrma.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcistrmb.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcistrmf.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcistrmz.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcitem.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dclist.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcmetinf.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcobject.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcofsetl.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcostrma.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcostrmb.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcostrmf.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcostrmz.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcovlay.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcpcache.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcpixel.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcpixseq.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcpxitem.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcrleccd.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcrlecce.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcrlecp.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcrledec.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcrledrg.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcrleenc.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcrleerg.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcrlerp.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcsequen.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcstack.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcswap.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dctag.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dctagkey.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dctk.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dctypes.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcuid.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcvm.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcvr.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcvrae.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcvras.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcvrat.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcvrcs.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcvrda.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcvrds.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcvrdt.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcvrfd.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcvrfl.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcvris.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcvrlo.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcvrlt.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcvrobow.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcvrof.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcvrpn.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcvrpobw.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcvrsh.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcvrsl.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcvrss.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcvrst.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcvrtm.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcvrui.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcvrul.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcvrulup.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcvrus.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcvrut.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/dcmtk/dcmdata" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/include/dcmtk/dcmdata/dcxfer.h")
