# Install script for directory: C:/Work/dcmtk-3.5.4/dcmdata/apps

# Set the install prefix
IF(NOT DEFINED CMAKE_INSTALL_PREFIX)
  SET(CMAKE_INSTALL_PREFIX "C:/Work/dcmtk-3.5.4/../dcmtk-3.5.4-win32-i386")
ENDIF(NOT DEFINED CMAKE_INSTALL_PREFIX)
STRING(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
IF(NOT CMAKE_INSTALL_CONFIG_NAME)
  IF(BUILD_TYPE)
    STRING(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  ELSE(BUILD_TYPE)
    SET(CMAKE_INSTALL_CONFIG_NAME "Release")
  ENDIF(BUILD_TYPE)
  MESSAGE(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
ENDIF(NOT CMAKE_INSTALL_CONFIG_NAME)

# Set the component getting installed.
IF(NOT CMAKE_INSTALL_COMPONENT)
  IF(COMPONENT)
    MESSAGE(STATUS "Install component: \"${COMPONENT}\"")
    SET(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  ELSE(COMPONENT)
    SET(CMAKE_INSTALL_COMPONENT)
  ENDIF(COMPONENT)
ENDIF(NOT CMAKE_INSTALL_COMPONENT)

FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/apps/dcm2xml.dtd")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/data" TYPE FILE FILES "C:/Work/dcmtk-3.5.4/dcmdata/apps/dumppat.txt")
SET(dcm2xml_BUILD_NAME_Debug "Debug/dcm2xml.exe")
SET(dcm2xml_BUILD_NAME_Release "Release/dcm2xml.exe")
SET(dcm2xml_BUILD_NAME_MinSizeRel "MinSizeRel/dcm2xml.exe")
SET(dcm2xml_BUILD_NAME_RelWithDebInfo "RelWithDebInfo/dcm2xml.exe")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE EXECUTABLE FILES "C:/Work/dcmtk-3.5.4/dcmdata/apps/${dcm2xml_BUILD_NAME_${CMAKE_INSTALL_CONFIG_NAME}}")
SET(dcm2xml_REMAPPED_NAME_Debug "dcm2xml.exe")
SET(dcm2xml_REMAPPED_NAME_Release "dcm2xml.exe")
SET(dcm2xml_REMAPPED_NAME_MinSizeRel "dcm2xml.exe")
SET(dcm2xml_REMAPPED_NAME_RelWithDebInfo "dcm2xml.exe")
SET(dcmconv_BUILD_NAME_Debug "Debug/dcmconv.exe")
SET(dcmconv_BUILD_NAME_Release "Release/dcmconv.exe")
SET(dcmconv_BUILD_NAME_MinSizeRel "MinSizeRel/dcmconv.exe")
SET(dcmconv_BUILD_NAME_RelWithDebInfo "RelWithDebInfo/dcmconv.exe")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE EXECUTABLE FILES "C:/Work/dcmtk-3.5.4/dcmdata/apps/${dcmconv_BUILD_NAME_${CMAKE_INSTALL_CONFIG_NAME}}")
SET(dcmconv_REMAPPED_NAME_Debug "dcmconv.exe")
SET(dcmconv_REMAPPED_NAME_Release "dcmconv.exe")
SET(dcmconv_REMAPPED_NAME_MinSizeRel "dcmconv.exe")
SET(dcmconv_REMAPPED_NAME_RelWithDebInfo "dcmconv.exe")
SET(dcmcrle_BUILD_NAME_Debug "Debug/dcmcrle.exe")
SET(dcmcrle_BUILD_NAME_Release "Release/dcmcrle.exe")
SET(dcmcrle_BUILD_NAME_MinSizeRel "MinSizeRel/dcmcrle.exe")
SET(dcmcrle_BUILD_NAME_RelWithDebInfo "RelWithDebInfo/dcmcrle.exe")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE EXECUTABLE FILES "C:/Work/dcmtk-3.5.4/dcmdata/apps/${dcmcrle_BUILD_NAME_${CMAKE_INSTALL_CONFIG_NAME}}")
SET(dcmcrle_REMAPPED_NAME_Debug "dcmcrle.exe")
SET(dcmcrle_REMAPPED_NAME_Release "dcmcrle.exe")
SET(dcmcrle_REMAPPED_NAME_MinSizeRel "dcmcrle.exe")
SET(dcmcrle_REMAPPED_NAME_RelWithDebInfo "dcmcrle.exe")
SET(dcmdrle_BUILD_NAME_Debug "Debug/dcmdrle.exe")
SET(dcmdrle_BUILD_NAME_Release "Release/dcmdrle.exe")
SET(dcmdrle_BUILD_NAME_MinSizeRel "MinSizeRel/dcmdrle.exe")
SET(dcmdrle_BUILD_NAME_RelWithDebInfo "RelWithDebInfo/dcmdrle.exe")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE EXECUTABLE FILES "C:/Work/dcmtk-3.5.4/dcmdata/apps/${dcmdrle_BUILD_NAME_${CMAKE_INSTALL_CONFIG_NAME}}")
SET(dcmdrle_REMAPPED_NAME_Debug "dcmdrle.exe")
SET(dcmdrle_REMAPPED_NAME_Release "dcmdrle.exe")
SET(dcmdrle_REMAPPED_NAME_MinSizeRel "dcmdrle.exe")
SET(dcmdrle_REMAPPED_NAME_RelWithDebInfo "dcmdrle.exe")
SET(dcmdump_BUILD_NAME_Debug "Debug/dcmdump.exe")
SET(dcmdump_BUILD_NAME_Release "Release/dcmdump.exe")
SET(dcmdump_BUILD_NAME_MinSizeRel "MinSizeRel/dcmdump.exe")
SET(dcmdump_BUILD_NAME_RelWithDebInfo "RelWithDebInfo/dcmdump.exe")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE EXECUTABLE FILES "C:/Work/dcmtk-3.5.4/dcmdata/apps/${dcmdump_BUILD_NAME_${CMAKE_INSTALL_CONFIG_NAME}}")
SET(dcmdump_REMAPPED_NAME_Debug "dcmdump.exe")
SET(dcmdump_REMAPPED_NAME_Release "dcmdump.exe")
SET(dcmdump_REMAPPED_NAME_MinSizeRel "dcmdump.exe")
SET(dcmdump_REMAPPED_NAME_RelWithDebInfo "dcmdump.exe")
SET(dcmftest_BUILD_NAME_Debug "Debug/dcmftest.exe")
SET(dcmftest_BUILD_NAME_Release "Release/dcmftest.exe")
SET(dcmftest_BUILD_NAME_MinSizeRel "MinSizeRel/dcmftest.exe")
SET(dcmftest_BUILD_NAME_RelWithDebInfo "RelWithDebInfo/dcmftest.exe")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE EXECUTABLE FILES "C:/Work/dcmtk-3.5.4/dcmdata/apps/${dcmftest_BUILD_NAME_${CMAKE_INSTALL_CONFIG_NAME}}")
SET(dcmftest_REMAPPED_NAME_Debug "dcmftest.exe")
SET(dcmftest_REMAPPED_NAME_Release "dcmftest.exe")
SET(dcmftest_REMAPPED_NAME_MinSizeRel "dcmftest.exe")
SET(dcmftest_REMAPPED_NAME_RelWithDebInfo "dcmftest.exe")
SET(dcmgpdir_BUILD_NAME_Debug "Debug/dcmgpdir.exe")
SET(dcmgpdir_BUILD_NAME_Release "Release/dcmgpdir.exe")
SET(dcmgpdir_BUILD_NAME_MinSizeRel "MinSizeRel/dcmgpdir.exe")
SET(dcmgpdir_BUILD_NAME_RelWithDebInfo "RelWithDebInfo/dcmgpdir.exe")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE EXECUTABLE FILES "C:/Work/dcmtk-3.5.4/dcmdata/apps/${dcmgpdir_BUILD_NAME_${CMAKE_INSTALL_CONFIG_NAME}}")
SET(dcmgpdir_REMAPPED_NAME_Debug "dcmgpdir.exe")
SET(dcmgpdir_REMAPPED_NAME_Release "dcmgpdir.exe")
SET(dcmgpdir_REMAPPED_NAME_MinSizeRel "dcmgpdir.exe")
SET(dcmgpdir_REMAPPED_NAME_RelWithDebInfo "dcmgpdir.exe")
SET(dcmodify_BUILD_NAME_Debug "Debug/dcmodify.exe")
SET(dcmodify_BUILD_NAME_Release "Release/dcmodify.exe")
SET(dcmodify_BUILD_NAME_MinSizeRel "MinSizeRel/dcmodify.exe")
SET(dcmodify_BUILD_NAME_RelWithDebInfo "RelWithDebInfo/dcmodify.exe")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE EXECUTABLE FILES "C:/Work/dcmtk-3.5.4/dcmdata/apps/${dcmodify_BUILD_NAME_${CMAKE_INSTALL_CONFIG_NAME}}")
SET(dcmodify_REMAPPED_NAME_Debug "dcmodify.exe")
SET(dcmodify_REMAPPED_NAME_Release "dcmodify.exe")
SET(dcmodify_REMAPPED_NAME_MinSizeRel "dcmodify.exe")
SET(dcmodify_REMAPPED_NAME_RelWithDebInfo "dcmodify.exe")
SET(dump2dcm_BUILD_NAME_Debug "Debug/dump2dcm.exe")
SET(dump2dcm_BUILD_NAME_Release "Release/dump2dcm.exe")
SET(dump2dcm_BUILD_NAME_MinSizeRel "MinSizeRel/dump2dcm.exe")
SET(dump2dcm_BUILD_NAME_RelWithDebInfo "RelWithDebInfo/dump2dcm.exe")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE EXECUTABLE FILES "C:/Work/dcmtk-3.5.4/dcmdata/apps/${dump2dcm_BUILD_NAME_${CMAKE_INSTALL_CONFIG_NAME}}")
SET(dump2dcm_REMAPPED_NAME_Debug "dump2dcm.exe")
SET(dump2dcm_REMAPPED_NAME_Release "dump2dcm.exe")
SET(dump2dcm_REMAPPED_NAME_MinSizeRel "dump2dcm.exe")
SET(dump2dcm_REMAPPED_NAME_RelWithDebInfo "dump2dcm.exe")
SET(pdf2dcm_BUILD_NAME_Debug "Debug/pdf2dcm.exe")
SET(pdf2dcm_BUILD_NAME_Release "Release/pdf2dcm.exe")
SET(pdf2dcm_BUILD_NAME_MinSizeRel "MinSizeRel/pdf2dcm.exe")
SET(pdf2dcm_BUILD_NAME_RelWithDebInfo "RelWithDebInfo/pdf2dcm.exe")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE EXECUTABLE FILES "C:/Work/dcmtk-3.5.4/dcmdata/apps/${pdf2dcm_BUILD_NAME_${CMAKE_INSTALL_CONFIG_NAME}}")
SET(pdf2dcm_REMAPPED_NAME_Debug "pdf2dcm.exe")
SET(pdf2dcm_REMAPPED_NAME_Release "pdf2dcm.exe")
SET(pdf2dcm_REMAPPED_NAME_MinSizeRel "pdf2dcm.exe")
SET(pdf2dcm_REMAPPED_NAME_RelWithDebInfo "pdf2dcm.exe")
SET(xml2dcm_BUILD_NAME_Debug "Debug/xml2dcm.exe")
SET(xml2dcm_BUILD_NAME_Release "Release/xml2dcm.exe")
SET(xml2dcm_BUILD_NAME_MinSizeRel "MinSizeRel/xml2dcm.exe")
SET(xml2dcm_BUILD_NAME_RelWithDebInfo "RelWithDebInfo/xml2dcm.exe")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE EXECUTABLE FILES "C:/Work/dcmtk-3.5.4/dcmdata/apps/${xml2dcm_BUILD_NAME_${CMAKE_INSTALL_CONFIG_NAME}}")
SET(xml2dcm_REMAPPED_NAME_Debug "xml2dcm.exe")
SET(xml2dcm_REMAPPED_NAME_Release "xml2dcm.exe")
SET(xml2dcm_REMAPPED_NAME_MinSizeRel "xml2dcm.exe")
SET(xml2dcm_REMAPPED_NAME_RelWithDebInfo "xml2dcm.exe")
